version: '3'
services:
  protoc:
    build:
      context: ./ 
      dockerfile: ./Dockerfile.protoc
    volumes:
      - ./:/app
    working_dir: /app
  server:
    build:
      context: ./ 
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/app
      - ./pb:/go/src/github/ota42y/microservices_apis/grpc/pb/app
    working_dir: /app
    command: ["go", "run", "main.go"]
  client:
    build:
      context: ./ 
      dockerfile: ./Dockerfile
    volumes:
      - ./client:/app
      - ./pb:/go/src/github/ota42y/microservices_apis/grpc/pb/app
    working_dir: /app
    command: ["go", "run", "main.go"]
    links: 
      - "server:server_host"